name: Run Cypress Tests

on:
  push:
  schedule:
    - cron: "0 0 * * 5"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run tests with Cypress
      uses: cypress-io/github-action@v2
      with:
        record: true
        start: npm start
        wait-on: 'https://marketplace.amalitech-dev.net/'

      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}git 